apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-depl.yaml
  - nginx-service.yaml

commonAnnotations: 
   owner: priyanshuyadav@gmail.com

images:
  - name: nginx
    newTag: "1.23"