apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    component: postgres-deployment
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  type: NodePort
